/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description List all entities with optional filtering by type and status.
         */
        get: operations["list_entities_entities_get"];
        put?: never;
        /**
         * Create Entity
         * @description Create a new entity.
         */
        post: operations["create_entity_entities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description Get a single entity by ID.
         */
        get: operations["get_entity_entities__entity_id__get"];
        /**
         * Update Entity
         * @description Update an existing entity.
         */
        put: operations["update_entity_entities__entity_id__put"];
        post?: never;
        /**
         * Delete Entity
         * @description Delete an entity.
         */
        delete: operations["delete_entity_entities__entity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Observations
         * @description List observations with optional filtering.
         */
        get: operations["list_observations_observations_get"];
        put?: never;
        /**
         * Create Observation
         * @description Create a new observation.
         */
        post: operations["create_observation_observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List projects with optional status filtering.
         */
        get: operations["list_projects_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Experiments
         * @description List experiments with optional status filtering.
         */
        get: operations["list_experiments_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Metrics
         * @description List metrics with optional filtering by name and date range.
         */
        get: operations["list_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List recent sessions.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Entity */
        Entity: {
            type: components["schemas"]["EntityType"];
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EntityCreate */
        EntityCreate: {
            type: components["schemas"]["EntityType"];
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "person" | "goal" | "system" | "value" | "decision" | "priority" | "tool";
        /**
         * EntityUpdate
         * @description Update model for entities. All fields optional except type which cannot be changed.
         */
        EntityUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** Experiment */
        Experiment: {
            /** Name */
            name: string;
            /** Intervention */
            intervention: string;
            /** Success Criteria */
            success_criteria: string;
            /** @default running */
            status: components["schemas"]["ExperimentStatus"];
            /** Hypothesis Id */
            hypothesis_id?: string | null;
            /** Metrics To Track */
            metrics_to_track?: string[];
            /** Outcome Summary */
            outcome_summary?: string | null;
            /** Outcome Data */
            outcome_data?: {
                [key: string]: unknown;
            } | null;
            /** Related Projects */
            related_projects?: string[];
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "running" | "completed" | "abandoned";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Metric */
        Metric: {
            /** Date */
            date: string;
            /** Metric Name */
            metric_name: string;
            /** Value */
            value: number;
            /** Source */
            source: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** Observation */
        Observation: {
            type: components["schemas"]["ObservationType"];
            /** Content */
            content: string;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence?: string[];
            /** @default active */
            status: components["schemas"]["ObservationStatus"];
            /** Related Entities */
            related_entities?: string[];
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Session Id */
            session_id: string | null;
        };
        /** ObservationCreate */
        ObservationCreate: {
            type: components["schemas"]["ObservationType"];
            /** Content */
            content: string;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence?: string[];
            /** @default active */
            status: components["schemas"]["ObservationStatus"];
            /** Related Entities */
            related_entities?: string[];
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * ObservationStatus
         * @enum {string}
         */
        ObservationStatus: "active" | "validated" | "refuted" | "outdated";
        /**
         * ObservationType
         * @enum {string}
         */
        ObservationType: "pattern" | "correlation" | "hypothesis" | "insight" | "preference";
        /** Project */
        Project: {
            /** Name */
            name: string;
            status: components["schemas"]["ProjectStatus"];
            /** Priority */
            priority?: number | null;
            /** Goal Alignment */
            goal_alignment?: string[];
            /** Current Phase */
            current_phase?: string | null;
            /** Blockers */
            blockers?: string[];
            /** Next Action */
            next_action?: string | null;
            /** Observations */
            observations?: string[];
            /** Notes */
            notes?: string | null;
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "paused" | "completed" | "abandoned";
        /** Session */
        Session: {
            /** Summary */
            summary?: string | null;
            /** Session Observations */
            session_observations?: string | null;
            /** Action Items */
            action_items?: string[];
            /**
             * Followup Needed
             * @default false
             */
            followup_needed: boolean;
            /** Followup Items */
            followup_items?: string[];
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_entities_entities_get: {
        parameters: {
            query?: {
                type?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entity_entities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entity_entities__entity_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entity_entities__entity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_observations_observations_get: {
        parameters: {
            query?: {
                status?: string | null;
                obs_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_observation_observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_experiments_experiments_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_metrics_metrics_get: {
        parameters: {
            query?: {
                metric_name?: string | null;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
